import argparse, os, platform, subprocess, sys, tempfile
from filecmp import dircmp
from pathlib import Path


def capture(command, **kwargs):
	stringified = [str(c) for c in command]
	print(stringified, flush=True)
	try:
		return subprocess.run(stringified, **{
			'capture_output': True,
			'check': True,
			'encoding': 'utf-8',
			**kwargs
		})
	except subprocess.CalledProcessError as err:
		raise RuntimeError('command {} failed with exit code {} and stderr:\n{}'.format(
			stringified,
			err.returncode,
			err.stderr
		))

def find_symstore():
	candidates = [
		Path(os.environ.get('ProgramFiles')) / 'Windows Kits' / '10' / 'Debuggers' / 'x64' / 'symstore.exe',
		Path(os.environ.get('ProgramFiles(x86)')) / 'Windows Kits' / '10' / 'Debuggers' / 'x64' / 'symstore.exe',
	]
	
	for candidate in candidates:
		if candidate.exists():
			return candidate
	
	raise RuntimeError('could not locate symstore.exe')

def find_prefix(lines, prefix):
	return list([
		line.removeprefix(prefix)
		for line in lines
		if line.startswith(prefix)
	])

def mark_types(parent, items):
	return [
		f'[DIRECTORY] {item}' if (parent / item).is_dir() else f'[FILE] {item}'
		for item in items
	]

def diff_trees(actual, expected, **kwargs):
	diff = dircmp(actual, expected, **kwargs)
	
	actual_only = diff.left_only
	expected_only = diff.right_only
	
	prepend_prefix = lambda items: [f'{subdir}/{item}' for item in items]
	for subdir, subdir_diff in diff.subdirs.items():
		actual_only += prepend_prefix(subdir_diff.left_only)
		expected_only += prepend_prefix(subdir_diff.right_only)
	
	return {
		'actual_only': sorted(mark_types(actual, actual_only)),
		'expected_only': sorted(mark_types(expected, expected_only)),
		'count': len(actual_only) + len(expected_only)
	}


# Verify that we are running under Windows
if platform.system() != 'Windows':
	print('Error: this validation script is designed to run under Windows.')
	sys.exit(1)

# Parse our command-line arguments
parser = argparse.ArgumentParser()
parser.add_argument('indir', help='Path to the input directory containing indexed symbol files')
args = parser.parse_args()
indir = Path(args.indir)

# Create a temporary directory to hold the directory structure generated by `symstore.exe`
with tempfile.TemporaryDirectory() as tempdir:
	
	# Run symstore.exe to generate our ground truth data
	# (Note that we just hardcode the most common path to `symstore.exe` here rather than detecting the location)
	symstore = find_symstore()
	output = capture([
		symstore, 'add',
		'-:NOREFS', '/r', '/o',
		'/f', indir,
		'/s', tempdir,
		'/t', 'Validation'
	])
	
	# Verify that the specified input directory actually contained symbol files
	lines = output.stdout.splitlines()
	stored = int(find_prefix(lines, 'SYMSTORE: Number of files stored = ')[0].strip())
	if stored == 0:
		print(f'Error: no symbol files found in input directory {indir}')
	
	# Identify whether any symbol files were ignored (this indicates that our indexer tool failed to reject them)
	ignored = find_prefix(lines, 'SYMSTORE MESSAGE: Skipping file ')
	ignored = sorted([str(Path(file).relative_to(indir)) for file in ignored])
	ignored = [file for file in ignored if not file.startswith('pingme.txt')]
	if len(ignored) > 0:
		print(f'\nValidation error: symstore.exe identified {len(ignored)} files that should have been ignored!')
		print('\nThese symbol files were supposed to be ignored:')
		print('- ' + '\n- '.join([file for file in ignored]))
	
	# Compare the ground truth directory structure to our input directory structure
	# (Note that we ignore the `000Admin` directory, which just holds transaction metadata)
	diff = diff_trees(indir, Path(tempdir) , ignore=['000Admin'])
	if diff['count'] > 0:
		print('\nValidation error: the directory structures do not match!')
		
		print(f'\n{ len(diff['actual_only']) } items only exist in the input directory:')
		if len(diff['actual_only']) > 0:
			print('- ' + '\n- '.join(diff['actual_only']))
		
		print(f'\n{ len(diff['expected_only']) } items only exist in the symstore.exe output:')
		if len(diff['expected_only']) > 0:
			print('- ' + '\n- '.join(diff['expected_only']))
	
	print('\nValidation complete.')
